Project 10(Лопатин, Панасовец)
dbms-class/csc-2020-team-all pull request #2
Opened 2020-10-29 17:02 UTC by apat1n

2020-11-02 19:41 UTC, ArtemSorokin commented on project10/29_10_2020.sql
> +	vehicle_type TEXT NOT NULL,
Не вижу связи со справочником vehicle_type, на который, по идее, от этого поля должен быть референс.

2020-11-02 19:41 UTC, ArtemSorokin commented on project10/29_10_2020.sql
> +	id INT NOT NULL UNIQUE, -- мы не допускаем повторяющихся идентификаторов
Мне кажется, во всех таблицах стоит делать PRIMARY KEY, тогда они автоматом станут UNIQUE и NOT NULL.

2020-11-02 19:41 UTC, ArtemSorokin commented on project10/29_10_2020.sql
> +-- Маршрут между начальной initial_stop остановкой и final_stop остановкой с номером ID для типа ТС vehicle_type
Опять-таки хочется, чтобы поле vehicle_type ссылалось на таблицу с типами ТС, а initial_stop и final_stop — на таблицу остановок (в следующих таблицах аналогично).

2020-11-02 19:41 UTC, ArtemSorokin commented on project10/29_10_2020.sql
> +	platform_number INT NOT NULL,
Точно ли номер платформы — int без ограничений?

2020-11-02 21:11 UTC, panslava commented on project10/29_10_2020.sql
> +-- Маршрут между начальной initial_stop остановкой и final_stop остановкой с номером ID для типа ТС vehicle_type
Да, нам хотелось расставить и Primary ключи и Foreign ключи, и мы даже начали это делать, но потом прочитали задание

```
 - Цель B: всё что есть в цели A + код на SQL создающий эти таблицы, с типами данных у атрибутов.
  - Цель C: всё что есть в цели B + CHECK/NOT NULL ограничения атрибуты, где сочтёте их нужными
  - Цель D: всё что есть в цели C + все возможные UNIQUE ключи в каждой таблице.
```

И поэтому подумали, что как будто мы ещё "не должны" знать про Foreign ключи и поэтому решили делать по заданию, вооот

2020-11-02 21:11 UTC, panslava commented on project10/29_10_2020.sql
> +	vehicle_type TEXT NOT NULL,
Ответил ниже

2020-11-02 21:11 UTC, panslava commented on project10/29_10_2020.sql
> +	id INT NOT NULL UNIQUE, -- мы не допускаем повторяющихся идентификаторов
Ответил ниже

2020-11-04 15:36 UTC, Tikhon239 reviewed
Исходя из начальных целей можно поставить отлично, но есть некоторые недочеты.

2020-11-04 15:36 UTC, Tikhon239 commented on project10/29_10_2020.sql
> +	release_year INT CHECK(release_year > 1800),
Мне кажется, из тз не следует это ограничения

2020-11-04 15:36 UTC, Tikhon239 commented on project10/29_10_2020.sql
> +	condition TEXT CHECK(condition IN ('исправен', 'некритические неисправности', 'требует ремонта')),
Как альтернатива можно было создать новый тип состояние, тогда можно было бы не писать проверку:
CREATE TYPE Сondition AS ENUM('исправен', 'некритические неисправности', 'требует ремонта');

2020-11-04 15:36 UTC, Tikhon239 commented on project10/29_10_2020.sql
> +	model_name TEXT NOT NULL
Про ссылку писать не буду, но в задании было написано описать связь между таблицами. Тут получается, что один транспорт является одной моделью, но бывают разные транспорты одной модели. Таким образом связь N:1  многие к одному.

Также, так как в дальнейшем vehicle будет ссылаться на vehicle_model, то таблица  vehicle_model должна создаваться раньше.

2020-11-04 15:36 UTC, Tikhon239 commented on project10/29_10_2020.sql
> +CREATE TABLE vehicle_type (
Мне кажется, эта таблица не нужна, так как типы транспорта практически не меняются, то есть можно было просто создать новый тип:
CREATE TYPE VehicleType AS ENUM('автобус', 'троллейбус', 'трамвай', 'ТУАХ', 'электробус');

2020-11-04 15:36 UTC, Tikhon239 commented on project10/29_10_2020.sql
> +	vehicle_type TEXT NOT NULL,
Не написано про тип связи таблиц

2020-11-04 15:36 UTC, Tikhon239 commented on project10/29_10_2020.sql
> +);
Я не очень понял, но в тз написано: "Платформы одной остановки пронумерованы начиная с 1". Не значит ли это, что платформы это какие то отдельные объекты?

2020-11-04 15:36 UTC, Tikhon239 commented on project10/29_10_2020.sql
> +);
Не прописаны виды связей между таблицами.

2020-11-04 15:36 UTC, Tikhon239 commented on project10/29_10_2020.sql
> +	time time NOT NULL,
В тз написано, что время должно быть указано: "с точностью до минуты", наверное можно навесить какой-то определенный формат.

2020-11-04 15:36 UTC, Tikhon239 commented on project10/29_10_2020.sql
> +	platform_number INT NOT NULL,
В тз написано: "Платформы одной остановки пронумерованы начиная с 1", на это нет проверки.

Мне кажется должен быть отдельный объект платформа, которая привязана к станции, имеет свой номер, а также хранит в себе состояние: занята или не занята.

2020-11-04 15:36 UTC, Tikhon239 commented on project10/29_10_2020.sql
> +);
Не прописаны виды связей между таблицами.

2020-11-04 15:36 UTC, Tikhon239 commented on project10/29_10_2020.sql
> +);
Не прописаны виды связей между таблицами.

Нет проверки на то, что тип транспорта подходит маршруту ( по тз у маршрута маршрута есть тип ТС, который его обслуживает)

2020-11-04 15:36 UTC, Tikhon239 commented on project10/29_10_2020.sql
> +	name TEXT NOT NULL
Имеет ли смысл сделать три поля под ФИО?

2020-11-04 15:36 UTC, Tikhon239 commented on project10/29_10_2020.sql
> +);
Не прописаны виды  связей между таблицами.

2020-11-04 15:36 UTC, Tikhon239 commented on project10/29_10_2020.sql
> +	assignment_id int NOT NULL,
Почему бы не сделать тут ссылку на driver_id. Тогда таблица assignment будет больше похожа на связывающую и не нужно будет поле id в assignment.

2020-11-04 15:36 UTC, Tikhon239 commented on project10/29_10_2020.sql
> +	id int NOT NULL UNIQUE, -- номера записей не повторяются
Мне кажется, это поле не нужно.

2020-11-04 15:36 UTC, Tikhon239 commented on project10/29_10_2020.sql
> +  	id INT NOT NULL UNIQUE, -- номер записи о статистике не повторяется
Мне кажется, это поле не нужно.

2020-11-04 15:36 UTC, Tikhon239 commented on project10/29_10_2020.sql
> +	assignment_id int NOT NULL,
По тз написано: "Пассажиры, заходя в салон ТС валидируют свои билеты". Мне кажется можно сделать ссылку на vehicle_id, по которому однозначно можно будет восстановить наряд.

2020-11-04 15:36 UTC, Tikhon239 commented on project10/29_10_2020.sql
> +);
Не прописан вид связи между таблицами.

2020-11-04 16:20 UTC, dyupon commented on project10/29_10_2020.sql
> +	id INT NOT NULL UNIQUE, -- мы не допускаем повторяющихся идентификаторов
serial? иначе не понятно, откуда каждый раз берется значение для id --  видимо, этот же комментарий работает для остальных таблиц

2020-11-04 16:20 UTC, dyupon commented on project10/29_10_2020.sql
> +	release_year INT CHECK(release_year > 1800),
а почему именно 1800?)

2020-11-04 16:20 UTC, dyupon commented on project10/29_10_2020.sql
> +	condition TEXT CHECK(condition IN ('исправен', 'некритические неисправности', 'требует ремонта')),
может, лучше было сделать поле перечислимым типом? эффективно происходил бы тот же самый check, а магических констант было бы меньше

2020-11-04 16:20 UTC, dyupon commented on project10/29_10_2020.sql
> +CREATE TABLE vehicle_type (
просто хочется констистентности --- вы либо на все поля, которые могли бы быть справочниками делаете check column in (...) как в случае с состоянием ТС или везде для этой цели честно используете справочники, как тут

2020-11-04 16:20 UTC, dyupon commented on project10/29_10_2020.sql
> +	capacity INT CHECK(capacity > 0)
вы сможете вставить сюда строку с capacity = NULL, а это нас, кажется, не устроит

2020-11-04 16:20 UTC, dyupon commented on project10/29_10_2020.sql
> +	available_platforms INT CHECK(available_platforms > 0)
same --- available_platforms при таком задании может быть NULL

2020-11-04 16:20 UTC, dyupon commented on project10/29_10_2020.sql
> +	assignment_id int NOT NULL,
кажется, что тут можно обойтись только assignment_id

2020-11-04 16:20 UTC, dyupon commented on project10/29_10_2020.sql
> +	price int NOT NULL CHECK(price > 0)
о, а тут есть ограничение на null) 
а стоимость действительно только целое число?

2020-11-05 14:21 UTC, dbarashev requested changes

2020-11-05 14:21 UTC, dbarashev commented on project10/29_10_2020.sql
> +	release_year INT CHECK(release_year > 1800),
автобусы, трамваи и троллейбусы не наблюдались в XVIII веке!

2020-11-05 14:21 UTC, dbarashev commented on project10/29_10_2020.sql
> +CREATE TABLE timetable (
Не хотите ли определить тут естественные ключи?

2020-11-05 14:21 UTC, dbarashev commented on project10/29_10_2020.sql
> +	actual_time time NOT NULL,
Как предполагается проверять согласованность этого атрибута с аналогичным, имеющимся в таблице timetable?

2020-11-11 13:43 UTC, dbarashev reviewed
@apat1n @panslava отметил эмоджей с глазками комментарии к недостаткам, причину и итерацию появления которых нужно выяснить

2020-11-11 13:43 UTC, dbarashev commented on project10/29_10_2020.sql
> +	release_year INT CHECK(release_year > 1800),
Я уверен, что именно 1800 взялось просто так, но в целом, именно четырехзначное число, а не, скажем, 0, имеет смысл, потому что приложения часто допускают ввод года двумя цифрами (например, 20 вместо 2020). Если такое значение так и пролетает от пользовательского интерфейса до таблицы, то вот такие вот ограничения позволят его отбросить.

2020-11-11 13:43 UTC, dbarashev commented on project10/29_10_2020.sql
> +CREATE TABLE statistics (
Не хотите ли определить тут естественный ключ?

2020-11-11 13:43 UTC, dbarashev commented on project10/29_10_2020.sql
> +CREATE TABLE assignment (
Не хотите ли определить тут естественные ключи?

2020-11-12 12:08 UTC, panslava commented on project10/29_10_2020.sql
> +	release_year INT CHECK(release_year > 1800),
Этот Check появился на втором занятии, когда меня ещё не было. Когда мне попался конце проект и увидел этот чек, мы ещё раз обсудили, и подумали, что как будто плохого он ничего не делает, и реально автомобилей до 19ого века не было, решили оставить

2020-11-12 12:27 UTC, panslava commented on project10/29_10_2020.sql
> +CREATE TABLE statistics (
Вообще да, (assignment_id, ticket_type) уникальны и однозначно определяют запись, можно было сделать это естественным ключом. Мне только не очень понятно, когда суррогатные ключи хорошо использовать, а когда плохо

Проблема появилась на последней итерации

2020-11-12 12:49 UTC, panslava commented on project10/29_10_2020.sql
> +	actual_time time NOT NULL,
Да, вероятно, стоило вместо expected_time сделать ссылку на запись в timetable: `timetable_id INT References Timetable(id)`, тогда бы было согласованно

Сложно сказать, с какой итерации пошла ошибка. На первой было написано `Ожидаемое время прибытия`, на второй `expected_time time`, и мы в конце написали `NOT NULL`

2020-11-12 13:59 UTC, apat1n commented on project10/29_10_2020.sql
> +CREATE TABLE assignment (
Судя по ТЗ (да и по логике), тут ключом будет UNIQUE(vehicle_id, route_id, driver_id, date).
При этом строже не получится: к примеру, сломался автобус 1 и из тройки (route_id, driver_id, date) мы не сможем получить vehicle_id на этом наряде. Аналогично, с любым другим полем.
Как-то не подумали об этом при проектировании(

2020-11-12 16:25 UTC, apat1n commented on project10/29_10_2020.sql
> +	actual_time time NOT NULL,
Проблема появилась при проектировании, когда не подумали, о том как эффективнее хранить информацию о том, когда, согласно расписанию, исполнитель наряда должен прибыть на остановку.

2020-11-25 22:02 UTC, dbarashev commented on project10/29_10_2020.sql
> +CREATE TABLE statistics (
> не очень понятно, когда суррогатные ключи хорошо использовать, а когда плохо

Суррогатный ключ нужен исключительно для внешних ссылок. Есть ссылки на таблицу -- используйте на здоровье. Но это не отменяет необходимость определения естественных ключей.

2020-11-25 22:02 UTC, dbarashev commented on project10/29_10_2020.sql
> +	price REAL NOT NULL CHECK(price > 0)
Любителям использовать типы с плавающей точкой для денежных вычислений предлагается викторина.
Что будет в результате этого запроса, считающего среднее арифметическое шести чисел?

```
SELECT
  avg(n)                 AS average,
  avg(n) = 5             AS is_average_five,
  avg(n) - floor(avg(n)) AS but_wtf
FROM (
  VALUES        -- эта и последующие строки формируют "таблицу" t(n) из которой делается выборка. 
                -- В ней шесть значений, которые в сумме дают ровно 30.
     (5   :: FLOAT),
     (5.1 :: FLOAT),
     (5.3 :: FLOAT),
     (5   :: FLOAT),
     (5.4 :: FLOAT),
     (4.2 :: FLOAT)
) t(n);
```

2020-11-25 22:02 UTC, dbarashev commented on project10/29_10_2020.sql
> +CREATE TABLE assignment (
> UNIQUE(vehicle_id, route_id, driver_id, date)

но это же никак не помешает тому же автобусу или тому же водителю в этот же день отправиться на другой маршрут. 

> сломался автобус 1 и из тройки (route_id, driver_id, date) мы не сможем получить vehicle_id на этом наряде

Сломался автобус -- наряд закончен, выписывайте другой, скорее всего, с другим водителем. Но мы всё же не рассматриваем такие сложные случаи, если они не предусмотрены ТЗ, Так то в реальной жизни один автобус в день выполняет два наряда (а водитель один), но по нашему ТЗ один наряд в день.

2020-11-26 16:33 UTC, Bnaich commented on project10/29_10_2020.sql
> +CREATE TABLE vehicle_type (
Мы считаем, что типы ТС могут добавляться, поэтому удобнее оставить таблицу-справочник

2022-02-21 14:48 UTC, closed without merging